name: Deploy to Azure VM

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6

        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /home/azureuser/node-app
            git pull origin master
            npm install
            pm2 start app.js --name my-app || pm2 restart my-app
